#!/bin/bash
#SBATCH --job-name=igor_runs
#SBATCH --ntasks=1
#SBATCH --error=igorcollect-%j.err
#SBATCH --out=igorcollect-%j.out
#SBATCH --mem=128G
#SBATCH --partition=dhvi
#SBATCH --ntasks-per-node=1

module load Python/2.7.11
module load R/3.6.0

create_seq_table=" ~/findCDR/Create_seq_table.py"
data_path="/datacommons/dhvi/Generated_cdr3_seqs"

gunzip ${data_path}/seq_w_D.txt.gz

for file in cdr*
do
	tail -n 1 -q ${file} >> ${data_path}/distance_counts.txt
	cat seq_wo_${file} >> ${data_path}/seq_wo_D.txt
	cat seq_wd_${file} >> ${data_path}/seq_w_D.txt
	rm ${file} seq_w[od]_${file}
done

cd ${data_path}/

date > outdata.txt
wc -l seq_w_D.txt | cut -f 1 -d " " > linecount
sort seq_w_D.txt|uniq | wc -l |cut -f 1 -d " " > uniqlinecount

Rscript parse_data.R >> outdata.txt

cut -f 1 seq_w_D.txt | shuf -n 100000 | sed "s|^|>seq\n|" > tmpD.fasta
weblogo -f tmpD.fasta -A protein --errorbars NO  -o seqlogo_with_D.eps -F eps -U probability -s large
rm tmpD.fasta

cut -f 1 seq_wo_D.txt | shuf -n 100000 | sed "s|^|>seq\n|"> tmpWOD.fasta
weblogo -f tmpWOD.fasta --errorbars NO  -o seqlogo_without_D.eps -F eps -U probability -s large
rm tmpWOD.fasta

for i in $(seq 4 -1 0)
do
 grep -w "D=${i}" seq_w_D.txt | cut -f 1 | shuf -n 100000 | sed "s|^|>seq\n|" > D${i}tmp.fasta
 weblogo -f D${i}tmp.fasta -A protein --errorbars NO  -o D_${i}.eps -F eps -U probability -s large
 grep -w "D=${i}" seq_w_D.txt | cut -f 1 | sed "s|^|>seq\n|" > D${i}.fasta
 rm D${i}tmp.fasta
done

rm -f simulation_withD_matrix.txt
python2.7 ${create_seq_table} simulation_withD_matrix.txt seq_w_D.txt

python2.7 ${create_seq_table} simulation_withoutD_matrix.txt seq_wo_D.txt
rm seq_wo_D.txt


cut -f 1 ${data_path}/seq_w_D.txt | sed "s|^|>seqxxx\n|g" > AAtmp.fasta
~/findCDR/findCDR -i AAtmp.fasta -o ~/recalc_logo.txt -s ~/findCDR/seq_logo.txt -aa
rm AAtmp.fasta

gzip seq_w_D.txt
